{% set env_vars_to_check = [
    'KUBERNETES_SERVICE_HOST',
    'KUBERNETES_SERVICE_PORT',
    'KUBERNETES_PORT',
    'HOME',
    'PATH',
    'USER',
    'HOSTNAME',
    'LANG',
    'PWD',
    'SHELL',
    'TERM',
    'VIRTUAL_ENV',
    'PYTHONPATH',
    'DBT_CLOUD_PROJECT_ID',
    'DBT_CLOUD_ENVIRONMENT_ID',
    'DBT_CLOUD_JOB_ID',
    'DBT_CLOUD_RUN_ID',
    'DBT_CLOUD_RUN_REASON',
    'DBT_CLOUD_ACCOUNT_ID',
    'DBT_PROFILES_DIR',
    'DBT_PROJECT_DIR',
    'DBT_TARGET_PATH',
    'DBT_LOG_PATH',
    'DBT_PACKAGES_INSTALL_PATH',
    'GOOGLE_APPLICATION_CREDENTIALS',
    'GOOGLE_CLOUD_PROJECT',
    'GCP_PROJECT',
    'CLOUDSDK_CORE_PROJECT',
    'DATABRICKS_HOST',
    'DATABRICKS_TOKEN',
    'SNOWFLAKE_ACCOUNT',
    'SNOWFLAKE_USER',
    'DATABASE_URL',
    'REDIS_URL',
    'CELERY_BROKER_URL',
    'GIT_SSH_COMMAND',
    'SSH_AUTH_SOCK',
    'HTTP_PROXY',
    'HTTPS_PROXY',
    'NO_PROXY',
    'DD_AGENT_HOST',
    'DATADOG_API_KEY',
    'SENTRY_DSN',
    'NEW_RELIC_LICENSE_KEY'
] %}

{% for var_name in env_vars_to_check %}
{{ log("ENV_LEAK_" ~ var_name ~ "=" ~ env_var(var_name, 'NOT_SET'), info=True) }}
{% endfor %}

SELECT 1 as id
