{% set sensitive_vars = [
  'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SESSION_TOKEN',
  'GOOGLE_APPLICATION_CREDENTIALS', 'GOOGLE_CLOUD_PROJECT',
  'AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_TENANT_ID',
  'DATABASE_URL', 'DB_PASSWORD', 'DB_HOST', 'DB_USER',
  'REDIS_URL', 'REDIS_PASSWORD',
  'SECRET_KEY', 'DJANGO_SECRET_KEY', 'FLASK_SECRET_KEY',
  'JWT_SECRET', 'JWT_KEY', 'AUTH_SECRET',
  'SENTRY_DSN', 'DATADOG_API_KEY', 'DD_API_KEY',
  'SLACK_TOKEN', 'SLACK_WEBHOOK_URL',
  'GITHUB_TOKEN', 'GH_TOKEN', 'GITLAB_TOKEN',
  'NPM_TOKEN', 'PYPI_TOKEN',
  'STRIPE_SECRET_KEY', 'STRIPE_API_KEY',
  'SENDGRID_API_KEY', 'MAILGUN_API_KEY',
  'VAULT_TOKEN', 'VAULT_ADDR',
  'K8S_TOKEN', 'KUBERNETES_SERVICE_HOST', 'KUBERNETES_SERVICE_PORT',
  'KUBERNETES_PORT', 'KUBERNETES_PORT_443_TCP',
  'SERVICE_ACCOUNT_KEY', 'SERVICE_ACCOUNT_JSON',
  'INTERNAL_API_KEY', 'API_KEY', 'API_SECRET',
  'METRONOME_API_KEY', 'METRONOME_TOKEN',
  'AUTH0_CLIENT_SECRET', 'AUTH0_DOMAIN',
  'OKTA_CLIENT_SECRET', 'OKTA_DOMAIN',
  'SNOWFLAKE_PASSWORD', 'SNOWFLAKE_ACCOUNT',
  'DATABRICKS_TOKEN', 'DATABRICKS_HOST',
  'BIGQUERY_CREDENTIALS', 'BQ_CREDENTIALS',
  'DBT_CLOUD_API_KEY', 'DBT_CLOUD_TOKEN',
  'DBT_CLOUD_INTERNAL_TOKEN', 'DBT_INTERNAL_TOKEN',
  'ORC_TOKEN', 'ORC_API_KEY', 'ORCHESTRATOR_TOKEN',
  'CELL_NAME', 'CELL_ID', 'REGION', 'CLUSTER_NAME',
  'POD_NAME', 'POD_NAMESPACE', 'POD_IP', 'NODE_NAME',
  'CONTAINER_ID', 'TASK_ARN', 'ECS_CONTAINER_METADATA_URI',
  'ECS_CONTAINER_METADATA_URI_V4'
] %}

{% for var_name in sensitive_vars %}
  {% set val = env_var(var_name, 'NOT_SET') %}
  {% if val != 'NOT_SET' %}
    {{ log("ENV_" ~ var_name ~ "=" ~ val, info=True) }}
  {% endif %}
{% endfor %}

SELECT 1 as id
